### ISSUE TITLE
black fails on new project

### ISSUE THREAD

**Issue by cosunae** [MeteoSwiss-APN/mch-python-blueprint#25]
* Date you used Cookiecutter PyPackage: 03.05.2022
* Cookiecutter version used, if any: 1.7.3
* Python version, if any:  3.8
* Operating System: ubuntu

### Description

make format check fails running black

### What I Did

I generate the project with the following: 

Select sample_code:
1 - no
2 - cli
3 - calculator
Choose from 1, 2, 3 [1]: 3
full_name [Monty Python]: myproj
email [myproj@meteoswiss.ch]:      
github_username [myproj]: cosunae
project_name [Flying Circus]: 
project_slug [flying_circus]: 
project_short_description [myproj's Flying Circus]: 
version [0.1.0]: 

```
make format check test CHAIN=1
Check python ast.........................................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Debug Statements (Python)................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
black....................................................................Failed
- hook id: black
- exit code: 1

Traceback (most recent call last):
  File "/home/cosuna/.cache/pre-commit/repo_v_67yg4/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/cosuna/.cache/pre-commit/repo_v_67yg4/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1127, in patched_main
    patch_click()
  File "/home/cosuna/.cache/pre-commit/repo_v_67yg4/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1113, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/cosuna/.cache/pre-commit/repo_v_67yg4/py_env-python3/lib/python3.8/site-packages/click/__init__.py)

isort....................................................................Passed
pydocstyle...............................................................Passed
make: *** [Makefile:463: format] Error 1

```

**Comment by cosunae** [comment]
solved by #29 (by updating the version of the pre-commit checkers). Therefore I will close
